services:
  pong:
    container_name: pong
    build: .
    init: true
    working_dir: /pong
    volumes:
      - .:/pong
    command: tail -f /dev/null
    ports:
      - "8080:8080"
      - "3000:3000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge